### ISSUE TITLE
Where do I go to learn what the output means?

### ISSUE THREAD

**Issue by xDinomode** [pkg/profile#28]
I'm writing a web app and using /wg/wrk to stress test it along with this tool but don't understand the output. [Here's](http://sprunge.us/XHFh) the CPU profile output after running **wrk -t12 -c400 -d7s http://127.0.0.1:8080**

**Comment by davecheney** [comment]
Can you please paste the .svg output.

**Comment by xDinomode** [comment]
Not sure if you wanted the text output or an svg image but [here's the text output](http://sprunge.us/jKSb)

Also this is the stress tester's output in case that's relevant

```bash
Running 7s test @ http://127.0.0.1:9000
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   232.52ms  329.40ms   1.99s    87.67%
    Req/Sec   274.25    266.36     1.87k    89.10%
  21381 requests in 7.10s, 7.77MB read
  Socket errors: connect 0, read 0, write 0, timeout 1
Requests/sec:   3010.93
Transfer/sec:      1.09MB

```

**Comment by davecheney** [comment]
Looking at that profile it looks like most of the time is being spent in
writing to the network, this doesn't look unexpected because this is a web
server after all.

**Comment by xDinomode** [comment]
@davecheney Yeah It's a simple web server but I was just curious as to what the numbers mean. Thanks anyway.
