### ISSUE TITLE
profile a project with multiple files in go

### ISSUE THREAD

**Issue by chakpongchung** [pkg/profile#32]
https://github.com/bluesea147/6.824

I tried using the package to profile this project. It cannot build the binary needed for the pprof.

Is it one of the designed use cases of this package?

One of the ways to run this project is to : 
export GOPATH=/home/XXX/6.824
go get github.com/pkg/profile
go test -run Sequential

**Comment by davecheney** [comment]
go test directly supports generating profiles, you don't need this package.

**Comment by chakpongchung** [comment]
export GOPATH=/home/cpchung/learn/6.824
go get github.com/pkg/profile
go test -run Sequential -cpuprofile=./c.pprof


in this way? then how I can use the c.pprof? I cannot go build this project since there is no main() there.

Any example code with multiple files I can learn?
