### ISSUE TITLE
Is it possible to enable two profiles at the same time.

### ISSUE THREAD

**Issue by aambati** [pkg/profile#38]
I would like to profile both heap and cpu at the same time. It seems to be possible (although i have not tried) with runtime/pprof package API. I have tried profile.Start(opt, profile.CPUProfile, profile.MemProfile), that only produced mem.pprof file. Quick scan of the code (switch statement) makes me think it is not possible

**Comment by davecheney** [comment]
No, this is not possible by design. Enabling multiple profiles at one time
generates incorrect results.
