### ISSUE TITLE
TestProfile fails

### ISSUE THREAD

**Issue by legrostdg** [pkg/profile#39]
I'm trying to create a Debian package for `profile`. The test `TestProfile` fails during the build of the packages:

	go test -v -p 4 github.com/pkg/profile
    === RUN   TestProfile
    --- FAIL: TestProfile (1.75s)
	profile_test.go:174: default profile (cpu)
	profile_test.go:174: memory profile
	profile_test.go:174: memory profile (rate 2048)
	profile_test.go:174: double start
	profile_test.go:174: block profile
	profile_test.go:174: profile path
	profile_test.go:174: profile path error
	profile_test.go:194: stderr: wanted '[could not create initial output]', got '2017/05/09 06:50:47 profile: cpu profiling enabled, README.md/cpu.pprof
		2017/05/09 06:50:47 profile: cpu profiling disabled, README.md/cpu.pprof
		'
	profile_test.go:209: expected error
	profile_test.go:174: multiple profile sessions
	profile_test.go:174: profile quiet

**Comment by davecheney** [comment]
What happens if you skip the -v and -p flags

**Comment by legrostdg** [comment]
go test github.com/pkg/profile
    --- FAIL: TestProfile (1.78s)
	profile_test.go:174: default profile (cpu)
	profile_test.go:174: memory profile
	profile_test.go:174: memory profile (rate 2048)
	profile_test.go:174: double start
	profile_test.go:174: block profile
	profile_test.go:174: profile path
	profile_test.go:174: profile path error
	profile_test.go:194: stderr: wanted '[could not create initial output]', got '2017/05/09 07:42:52 profile: cpu profiling enabled, README.md/cpu.pprof
		2017/05/09 07:42:52 profile: cpu profiling disabled, README.md/cpu.pprof
		'
	profile_test.go:209: expected error
	profile_test.go:174: multiple profile sessions
	profile_test.go:174: profile quiet
    FAIL
    FAIL	github.com/pkg/profile	1.784s

**Comment by davecheney** [comment]
Ok, it was worth a shot, let me take a look at that test.

**Comment by legrostdg** [comment]
Thanks! Could you publish a new release with this fix?

**Comment by davecheney** [comment]
Done. https://github.com/pkg/profile/releases/tag/v1.2.1
