### ISSUE TITLE
parsing profile: unrecognized profile format in ubuntu

### ISSUE THREAD

**Issue by utkarshmani1997** [pkg/profile#43]
getting this error while running `go tool pprof -text ./jiva`
```./jiva: parsing profile: unrecognized profile format
failed to fetch any source profiles
```
binary build on go version 1.7.3 testing on go version 1.10

**Comment by davecheney** [comment]
Go 1.10 won’t understand a go 1.7 profile

**Comment by utkarshmani1997** [comment]
Ok, thanks @davecheney
