### ISSUE TITLE
How to profile loading of libraries ? 

### ISSUE THREAD

**Issue by fxfactorial** [pkg/profile#47]
Fantastic tool.

One thing, say I have a binary that is loading slowly from a massive amount of `imports` that may possibly be having side effects upon code being loaded. 

I don't see how to use `profile` here because I put `defer profile.Start().Stop()` at the beginning of `main` but that doesn't capture the loading/code execution of library code. 

thank you

**Comment by davecheney** [comment]
This is not possible with the profiling built into go because the text segment of the binary is demand paged into memory. 

If you are on Linux I suggest perf(1).

**Comment by davecheney** [comment]
Closing. Answered.

**Comment by fxfactorial** [comment]
@davecheney thank you for quick answer. Side question, there isn't an equvialent in go for like

```
__attribute__((constructor))
```
?

**Comment by davecheney** [comment]
Nope. Nothing like that. Please try go-nuts or slack for General go questions.
