### ISSUE TITLE
Usgin MemProfileAllocs sample in the readme

### ISSUE THREAD

**Issue by bitcodr** [pkg/profile#55]
In the readme, there is an example which is shows how to use `profile.MemProfileAllocs` in the Start function, but the sample is wrong and you'll get an error like 

`cannot use profile.MemProfileAllocs (type func() func(*profile.Profile)) as type func(*profile.Profile) in argument to profile.Start
`

And the readme should be 
`p := profile.Start(profile.MemProfileAllocs(), profile.ProfilePath("."), profile.NoShutdownHook)`

So if do you confirm it's wrong can I send a PR to fix the readme or the codebase?

**Comment by davecheney** [comment]
Opps. Thanks for spotting that. Fix coming up
