### ISSUE TITLE
Versioning and breaking change in `MemProfile{Heap,Allocs}` signatures

### ISSUE THREAD

**Issue by mmcloughlin** [pkg/profile#59]
Commit 3704c8d23324a3fc0771ad2c1cef0aa4e9459f6f changed the signatures of `MemProfile{Heap,Allocs}`. Is this going to require a `v2`?

**Comment by davecheney** [comment]
If it did, i'm sorry, but I'm not going to do the v2 nonsense. Sorry.

**Comment by mmcloughlin** [comment]
Not a problem, I was just curious how you intended to handle it.

**Comment by davecheney** [comment]
Thanks for catching it. It’s hard to remember back a year but if I did spot the comparison break, which I probably didn’t, I would have said “nah, not worth v2”. This is probably still true.

**Comment by mmcloughlin** [comment]
Yeah I think you're fine. I assume very few are affected and the fix is removing parens `()`. But you'd minimize the impact by tagging `v1.6.0` now.
