### ISSUE TITLE
No support to run multiple profile 

### ISSUE THREAD

**Issue by prakashettigar** [pkg/profile#62]
```
profile.Start(profile.MemProfile, profile.ProfilePath("."), profile.NoShutdownHook)
profile.Start(profile.CPUProfile, profile.ProfilePath("."), profile.NoShutdownHook)
```
Starting multiple profiles  throws an error :  ```profile: Start() already called```

**Comment by davecheney** [comment]
This is a deliberate design choice.

**Comment by 10sor** [comment]
@davecheney can you please explain why?

**Comment by davecheney** [comment]
Running multiple profiles at the same time causes interference.

**Comment by yonderblue** [comment]
@davecheney is the interference something that breaks or just skew results? For example with mem+cpu the coarse relative picture seems to hold up well in cases I've checked despite the overhead.

**Comment by davecheney** [comment]
It skews the results.

**Comment by LiranBri** [comment]
I suggest to add the explanation to the actual error, as it's not trivial as in fact it makes the pkg do more than just a convenient proxy to the native API, because the native API does allow running multiple profilers.

If you agree I can make the PR
